// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpHwYo9sGHlnnhi_u9NTwTHf4QhNECIMI',
    appId: '1:750857502624:web:72d3f21d93cfae38336ec5',
    messagingSenderId: '750857502624',
    projectId: 'view-veppora',
    authDomain: 'view-veppora.firebaseapp.com',
    storageBucket: 'view-veppora.firebasestorage.app',
    measurementId: 'G-V1TJEKGM1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_VHnWjXfygsRsmzSUBfOqyQb02QvwFpg',
    appId: '1:750857502624:android:ad7b9685f155f6f0336ec5',
    messagingSenderId: '750857502624',
    projectId: 'view-veppora',
    storageBucket: 'view-veppora.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrxnyvkfg1NPHydVm-sNfOIGc-eI6F6iQ',
    appId: '1:750857502624:ios:275a8e6d7f10654a336ec5',
    messagingSenderId: '750857502624',
    projectId: 'view-veppora',
    storageBucket: 'view-veppora.firebasestorage.app',
    iosClientId: '750857502624-l0dtl5kgr3csrn2qr6fe9n0mjgleb74f.apps.googleusercontent.com',
    iosBundleId: 'com.example.newversion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrxnyvkfg1NPHydVm-sNfOIGc-eI6F6iQ',
    appId: '1:750857502624:ios:275a8e6d7f10654a336ec5',
    messagingSenderId: '750857502624',
    projectId: 'view-veppora',
    storageBucket: 'view-veppora.firebasestorage.app',
    iosClientId: '750857502624-l0dtl5kgr3csrn2qr6fe9n0mjgleb74f.apps.googleusercontent.com',
    iosBundleId: 'com.example.newversion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpHwYo9sGHlnnhi_u9NTwTHf4QhNECIMI',
    appId: '1:750857502624:web:b063eda8d9ed759c336ec5',
    messagingSenderId: '750857502624',
    projectId: 'view-veppora',
    authDomain: 'view-veppora.firebaseapp.com',
    storageBucket: 'view-veppora.firebasestorage.app',
    measurementId: 'G-1C33PZD7CS',
  );
}
